### PR TITLE
ci: add master core install for lint/test/dev

### PR DESCRIPTION
**Pull request by efriis**

### CODE REVIEW

**Comment by efriis** [comment]
@cbornet integration tests seem to be failing for unrelated reason - let me know if it's due to a change in core!

**Comment by hemidactylus** [comment]
Hi, @efriis , thank you for taking care of this upgrade and spotting the test failure. It was indeed related to a randomness-induced flakiness, which is addressed in https://github.com/langchain-ai/langchain-datastax/pull/15. That should be merged momentarily - and this PR, once rebased, will certainly pass.

Thank you!

**Comment by cbornet** [comment]
@efriis #15 has been merged. Can you rebase the PR ?

**Comment by hemidactylus** [comment]
I should have been able to do it myself as one side was pure code and the other was pure dependencies. Could please @cbornet  or @efriis take a look?

**Review by cbornet — APPROVED** [review]

**Comment by efriis** [comment]
oops thanks for merging!

**Pull request merged**
