### PR TITLE
release permissions

### PR DESCRIPTION
**Pull request by efriis**

### CODE REVIEW

**Comment by efriis** [comment]
merging - this is required to make releases on github enterprise permissions!

**Comment by efriis** [comment]
actually looks like someone might need to review. @hemidactylus fyi this will need an approve and merge to allow releases in the future!

**Comment by hemidactylus** [comment]
@efriis done. I confess I am not sure what this does exactly (if I recall, the PyPI release process is already working - so perhaps this is about "releases" in the github sense?).
Anyway, here's my LGTM. Feel free to merge any time :)

**Comment by hemidactylus** [comment]
Oh, let me merge directly, no big deal

**Pull request merged**
